# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mangal < Formula
  desc "The ultimate CLI manga downloader!"
  homepage "https://github.com/metafates/mangal"
  version "3.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metafates/mangal/releases/download/v3.7.0/mangal_3.7.0_Darwin_x86_64.tar.gz"
      sha256 "5ed8a685628f1cd6bb10559d26916f91c28e0b89a482d83f8d9369e14fc9eeaf"

      def install
        bin.install "mangal"
        bash_completion.install "completions/mangal.bash" => "mangal"
        zsh_completion.install "completions/mangal.zsh" => "_mangal"
        fish_completion.install "completions/mangal.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metafates/mangal/releases/download/v3.7.0/mangal_3.7.0_Darwin_arm64.tar.gz"
      sha256 "815755e820c96bf1d70a7490082dfbf6c37bd394aa69a8f65b97f5c35e2e5e8c"

      def install
        bin.install "mangal"
        bash_completion.install "completions/mangal.bash" => "mangal"
        zsh_completion.install "completions/mangal.zsh" => "_mangal"
        fish_completion.install "completions/mangal.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/metafates/mangal/releases/download/v3.7.0/mangal_3.7.0_Linux_x86_64.tar.gz"
      sha256 "9d19e7b44391a21e7836f75a9dabd74f0b0abfc21fad8b56999a0a5f7405020b"

      def install
        bin.install "mangal"
        bash_completion.install "completions/mangal.bash" => "mangal"
        zsh_completion.install "completions/mangal.zsh" => "_mangal"
        fish_completion.install "completions/mangal.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/metafates/mangal/releases/download/v3.7.0/mangal_3.7.0_Linux_armv6.tar.gz"
      sha256 "7dc5aca3647eb79fa7e2318c074bff4a71c5dc2b66291b64eb154d4504f809e5"

      def install
        bin.install "mangal"
        bash_completion.install "completions/mangal.bash" => "mangal"
        zsh_completion.install "completions/mangal.zsh" => "_mangal"
        fish_completion.install "completions/mangal.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metafates/mangal/releases/download/v3.7.0/mangal_3.7.0_Linux_arm64.tar.gz"
      sha256 "79c266862d0a31ac548bc39ae7e2a0f7935801a5bafebd8855084c26b1bad810"

      def install
        bin.install "mangal"
        bash_completion.install "completions/mangal.bash" => "mangal"
        zsh_completion.install "completions/mangal.zsh" => "_mangal"
        fish_completion.install "completions/mangal.fish"
      end
    end
  end

  test do
    system "#{bin}/mangal -v"
  end
end
